/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-02-06 03:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/shop/bottom.jsp", Long.valueOf(1580959190684L));
    _jspx_dependants.put("/shop/top.jsp", Long.valueOf(1576636542355L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- login.jsp -->\n");
      out.write("<!--쇼핑몰 기능 \n");
      out.write("1. 상품\n");
      out.write("2. 장바구니: session을 활용한다.\n");
      out.write("3. 구매 \n");
      out.write("-->\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Simple Shopping Mall Demo</title>\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body topmargin=\"100\">\n");
      out.write('\n');

	String id = (String)session.getAttribute("idKey");
	
	String log="";
	if(id == null) log ="<a href=login.jsp>로그인</a>";
	else log = "<a href=logout.jsp>로그아웃</a>";

	String reg="";
	if(id == null) reg ="<a href=member.jsp>회원가입</a>";
	else reg = "<a href=memberUpdate.jsp>회원수정</a>";

      out.write("\n");
      out.write("<table align=\"center\" bgcolor=\"#080808\" width=\"55%\">\n");
      out.write("<tr bgcolor=\"#ffffff\">\n");
      out.write("  <th width=\"50%\" height=\"40%\"\n");
      out.write("  style=\"background-image: url(data/data10.jpg);\">\n");
      out.write(" WELCOME TO THE<br/>\n");
      out.write("  <span style=\"Font-size: 50pt; line-height: 200%; color: black;\" id=\"spanTag\" >햄버거 천국</span><br/>\n");
      out.write("  (the HAMBURGER HEAVEN)\n");
      out.write("  </th>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<table width=\"50%\" align=\"center\" bgcolor=\"#080808\" >\n");
      out.write("    <tr bgcolor=\"#ffffff\"> \n");
      out.write("    <th>");
      out.print(log);
      out.write("</th>\n");
      out.write("    <th>");
      out.print(reg);
      out.write("</th>\n");
      out.write("    <th><a href=\"productList.jsp\">상품목록</a></th>\n");
      out.write("    <th><a href=\"cartList.jsp\">장바구니</a></th>\n");
      out.write("    <th><a href=\"orderList.jsp\">구매목록</a></th>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<form method=\"post\" action=\"loginProc.jsp\">\n");
      out.write("<table width=\"50%\" align=\"center\" bgcolor=\"#FFFFFF\">\n");
      out.write("\t<tr bordercolor=\"black\">  \n");
      out.write("\t<td height=\"190\">\n");
      out.write("\t\t<table width=\"60%\" border=\"1\" align=\"center\">\n");
      out.write("\t\t<tr bordercolor=\"black\"> \n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\">로그인</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr  align=\"center\"> \n");
      out.write("\t\t\t<td width=\"47%\">ID</td>\n");
      out.write("\t\t\t<td width=\"53%\"><input name=\"id\" value=\"aaa\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr> \n");
      out.write("\t\t\t<td align=\"center\">Password</td>\n");
      out.write("\t\t\t<td align=\"center\"><input name=\"pwd\" value=\"1234\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr> \n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"login\">\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \n");
      out.write("\t\t<input type=\"reset\" value=\"reset\">\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<table width=\"75%\" align=\"center\" bgcolor=\"#080808\">\n");
      out.write("  \n");
      out.write("  <tr>\n");
      out.write("  <th><a href=\"admin/index.jsp\">관리자</a></th>\n");
      out.write("  </tr>\n");
      out.write("</table>");
      out.write("\n");
      out.write("</body>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
